export const locales = ["fr", "en", "ar"] as const;
export type Locale = (typeof locales)[number];
export type Messages = Record<string, string>;

export const defaultLocale: Locale = "fr";
export const localeCookie = "JOSHOP_LOCALE";

export function isLocale(value: unknown): value is Locale {
  return typeof value === "string" && locales.includes(value as Locale);
}

const fr: Messages = {
  "meta.title": "JoShop — Les gadgets malins venus de Chine",
  "meta.description": "Marketplace tunisienne de gadgets utiles importés de Chine pour la maison, les loisirs et le quotidien.",
  "common.home": "Accueil", "common.products": "Produits", "common.categories": "Catégories", "common.search": "Rechercher", "common.searchPlaceholder": "Rechercher un produit, une marque…", "common.account": "Compte", "common.cart": "Panier", "common.wishlist": "Favoris", "common.close": "Fermer", "common.menu": "Menu", "common.viewAll": "Tout voir", "common.discover": "Découvrir", "common.shopNow": "Acheter maintenant", "common.exploreDeals": "Voir les offres", "common.learnMore": "En savoir plus", "common.back": "Retour", "common.continueShopping": "Continuer mes achats", "common.quantity": "Quantité", "common.subtotal": "Sous-total", "common.shipping": "Livraison", "common.total": "Total", "common.remove": "Retirer", "common.color": "Couleur", "common.option": "Option", "common.stock": "Stock", "common.inStock": "En stock", "common.outOfStock": "Rupture de stock", "common.new": "Nouveau", "common.sale": "Promo", "common.recommended": "Recommandés", "common.priceLow": "Prix croissant", "common.priceHigh": "Prix décroissant", "common.topRated": "Mieux notés", "common.noResults": "Aucun résultat", "common.clearFilters": "Effacer les filtres",
  "nav.audio": "Audio", "nav.home": "Maison", "nav.mobility": "Mobilité électrique", "nav.gaming": "Gaming", "nav.connected": "Objets connectés", "nav.accessories": "Accessoires", "nav.deals": "Bons plans",
  "hero.eyebrow": "Gadgets de Chine / 2026", "hero.title": "Des gadgets qui simplifient le quotidien.", "hero.copy": "Audio, maison, gaming, objets connectés et accessoires importés de Chine, sélectionnés pour la Tunisie.",
  "home.categoriesEyebrow": "Explorer JoShop", "home.categoriesTitle": "Tout ce qu'il vous faut", "home.trendingEyebrow": "Les plus demandés", "home.trendingTitle": "Tendances du moment", "home.newEyebrow": "Fraîchement arrivés", "home.newTitle": "Nouveautés", "home.flashEyebrow": "Offres à durée limitée", "home.flashTitle": "Ventes flash", "home.mobilityEyebrow": "Bougez autrement", "home.mobilityTitle": "Mobilité électrique", "home.mobilityCopy": "Trottinettes et vélos électriques fiables, pensés pour les trajets urbains et les sorties du week-end.", "home.promoEyebrow": "Prix JoShop", "home.promoTitle": "Plus de trouvailles. Un budget maîtrisé.", "home.promoCopy": "Des gadgets utiles à prix accessibles, dans la limite des stocks disponibles.", "home.newsletterEyebrow": "Les nouvelles JoShop", "home.newsletterTitle": "Le bon gadget, au bon moment.", "home.newsletterCopy": "Nouveaux gadgets, guides et offres utiles directement dans votre boîte mail.", "home.newsletterLegal": "En vous inscrivant, vous acceptez de recevoir les actualités JoShop. Désinscription à tout moment.",
  "home.bestEyebrow": "Approuvés par nos clients", "home.bestTitle": "Meilleures ventes", "home.endsIn": "Se termine dans", "home.countdownLabel": "Fin de l’offre dans {hours} heures, {minutes} minutes et {seconds} secondes", "hero.products": "gadgets importés", "hero.categories": "catégories", "hero.support": "assistance commande", "newsletter.success": "Inscription confirmée. Bienvenue chez JoShop.", "newsletter.subscribe": "S’inscrire",
  "trust.secureTitle": "Paiement sécurisé", "trust.secureCopy": "Carte bancaire ou paiement à la livraison", "trust.deliveryTitle": "Livraison en Tunisie", "trust.deliveryCopy": "Tarif standard fixe de 7 TND", "trust.supportTitle": "Assistance locale", "trust.supportCopy": "Une équipe disponible pour vous aider", "trust.returnsTitle": "Retour simplifié", "trust.returnsCopy": "Demande de retour sous 14 jours",
  "product.addToCart": "Ajouter au panier", "product.buyNow": "Acheter maintenant", "product.added": "Produit ajouté au panier", "product.chooseOption": "Choisir une option", "product.specifications": "Caractéristiques techniques", "product.description": "Description", "product.reviews": "Avis clients", "product.verified": "Achat vérifié", "product.sku": "Référence", "product.youMayLike": "Vous aimerez aussi", "product.recentlyViewed": "Consultés récemment", "product.results": "produits", "product.filters": "Filtres", "product.brand": "Marque", "product.category": "Catégorie", "product.price": "Prix", "product.rating": "Note", "product.availability": "Disponibilité", "product.onlyDiscounted": "Produits en promotion", "product.sort": "Trier les produits", "product.viewImage": "Voir l’image {index} de {product}", "product.openImage": "Agrandir l’image du produit",
  "product.sold": "vendus", "product.onlyLeft": "Plus que {count} en stock", "product.ready": "En stock et prêt à expédier", "product.deliveryCopy": "Livraison en Tunisie sous 2 à 4 jours ouvrés — 7 TND", "product.paymentCopy": "Paiement à la livraison · Retours sous 14 jours", "wishlist.saved": "Ajouté aux favoris", "wishlist.removed": "Retiré des favoris", "wishlist.addAction": "Ajouter aux favoris", "wishlist.removeAction": "Retirer des favoris",
  "product.anyBrand": "Toutes les marques", "product.all": "Tous", "product.anyRating": "Toutes les notes", "product.inStockOnly": "En stock uniquement", "product.applyFilters": "Appliquer les filtres",
  "product.detailsEyebrow": "Tout savoir", "product.shippingCopy": "Livraison standard en 2 à 4 jours ouvrés au tarif fixe de 7 TND.", "product.returnsCopy": "Retournez le produit complet dans son état d’origine sous 14 jours.", "product.customerNotes": "L’avis de nos clients", "product.reviewsCount": "avis",
  "cart.title": "Votre panier", "cart.emptyTitle": "Votre panier est vide", "cart.emptyCopy": "Découvrez nos gadgets importés et trouvez celui qui vous simplifiera le quotidien.", "cart.summary": "Récapitulatif", "cart.checkout": "Passer la commande", "cart.standardShipping": "Livraison standard", "cart.standardShippingDetail": "Livraison en Tunisie — 7 TND", "cart.updated": "Panier mis à jour",
  "cart.selection": "Votre sélection", "cart.viewCart": "Voir le panier", "cart.items": "articles", "cart.discount": "Remise", "cart.taxNote": "Taxes incluses. Livraison standard fixe de 7 TND.",
  "wishlist.title": "Vos favoris", "wishlist.emptyTitle": "Aucun favori pour le moment", "wishlist.emptyCopy": "Enregistrez les produits qui vous intéressent pour les retrouver ici.",
  "wishlist.eyebrow": "Votre sélection", "wishlist.count": "produits enregistrés. Ajoutez-les directement au panier.",
  "checkout.title": "Finaliser la commande", "checkout.backToCart": "Retour au panier", "checkout.contact": "Coordonnées", "checkout.delivery": "Adresse de livraison", "checkout.payment": "Paiement", "checkout.orderSummary": "Votre commande", "checkout.placeOrder": "Confirmer la commande", "checkout.processing": "Traitement en cours…", "checkout.fullName": "Nom complet", "checkout.email": "E-mail", "checkout.phone": "Téléphone", "checkout.address": "Adresse", "checkout.city": "Ville", "checkout.governorate": "Gouvernorat", "checkout.postalCode": "Code postal", "checkout.country": "Pays", "checkout.cash": "Paiement à la livraison", "checkout.card": "Carte bancaire", "checkout.note": "Note de livraison (facultatif)", "checkout.standard": "Livraison standard — 7 TND", "checkout.express": "Livraison express — 15 TND",
  "checkout.emptyTitle": "Aucune commande à finaliser", "checkout.emptyCopy": "Ajoutez un produit avant de commencer.", "checkout.error": "Votre commande n’a pas pu être enregistrée.", "checkout.chooseGovernorate": "Choisir un gouvernorat", "checkout.deliveryMethod": "Mode de livraison", "checkout.standardTime": "2 à 4 jours ouvrés", "checkout.expressLabel": "Livraison express", "checkout.expressTime": "1 à 2 jours ouvrés", "checkout.cashCopy": "Payez à la réception de votre commande", "checkout.comingSoon": "Bientôt disponible", "checkout.secureCopy": "Vos informations sont chiffrées et sécurisées.",
  "order.received": "Commande reçue", "order.confirmed": "Commande confirmée", "order.thanks": "Merci, {name}. Nous vous tiendrons informé de son avancement.", "order.items": "Vos articles", "order.next": "Et maintenant ?", "order.nextCopy": "Nous confirmerons votre commande, la préparerons puis vous enverrons une mise à jour de livraison par e-mail.", "order.deliveryTo": "Livraison à", "order.number": "Commande", "order.track": "Suivre mes commandes", "account.title": "Mon compte", "account.orders": "Mes commandes",
  "account.ordersCopy": "Suivre les livraisons et consulter l’historique", "account.wishlistCopy": "Retrouver les produits que vous avez enregistrés", "account.addresses": "Adresses", "account.addressesCopy": "Gérer vos adresses de livraison", "account.personal": "Informations personnelles", "account.personalCopy": "Mettre à jour votre profil et vos coordonnées", "account.guest": "Aperçu du compte invité", "account.welcome": "Bienvenue chez JoShop.", "account.guestCopy": "Le paiement invité reste disponible. Ces espaces sont prêts à être reliés à un compte authentifié.", "account.profilePreview": "Aperçu du profil", "account.guestShopper": "Client invité", "account.market": "Marché", "account.tunisia": "Tunisie", "account.currency": "Devise préférée", "account.savedAddresses": "Adresses enregistrées", "account.noAddress": "Aucune adresse n’est enregistrée pour le paiement invité. Les coordonnées restent associées à chaque commande.", "account.orderHistory": "Historique des commandes", "account.placed": "Passée le", "account.viewDetails": "Voir les détails", "account.noOrders": "Aucune commande", "account.noOrdersCopy": "Votre historique apparaîtra ici.",
  "auth.fullName": "Nom complet", "auth.email": "E-mail", "auth.phone": "Téléphone (facultatif)", "auth.password": "Mot de passe", "auth.confirmPassword": "Confirmer le mot de passe", "auth.createAccount": "Créer mon compte", "auth.signIn": "Se connecter", "auth.signOut": "Se déconnecter", "auth.registering": "Création du compte…", "auth.signingIn": "Connexion…", "auth.haveAccount": "Vous avez déjà un compte ?", "auth.noAccount": "Vous n’avez pas encore de compte ?", "auth.passwordRules": "Au moins 8 caractères, avec une majuscule, une minuscule et un chiffre.", "auth.memberEyebrow": "Espace client", "auth.registerTitle": "Créez votre compte", "auth.registerCopy": "Regroupez vos commandes, gagnez du temps au paiement et retrouvez vos informations sur tous vos appareils.", "auth.loginTitle": "Heureux de vous revoir", "auth.loginCopy": "Connectez-vous pour retrouver vos commandes et vos coordonnées.", "auth.signInCopy": "Saisissez les identifiants de votre compte JoShop.", "auth.secureAccountCopy": "Vos identifiants sont protégés et votre panier invité reste disponible.", "auth.benefitOrders": "Toutes vos commandes au même endroit", "auth.benefitCheckout": "Coordonnées préremplies au paiement", "auth.benefitAddresses": "Adresses enregistrées dans votre profil", "auth.invalidRegistration": "Vérifiez vos informations et respectez les règles du mot de passe.", "auth.emailExists": "Un compte utilise déjà cette adresse e-mail. Connectez-vous.", "auth.invalidCredentials": "Adresse e-mail ou mot de passe incorrect.", "auth.databaseRequired": "La base de données doit être configurée pour créer un compte.", "auth.registrationFailed": "Impossible de créer le compte pour le moment. Réessayez.", "auth.loginFailed": "Impossible de vous connecter pour le moment. Réessayez.",
  "account.guestTitle": "Votre espace JoShop", "account.guestRegistrationCopy": "Créez un compte pour retrouver vos commandes et préremplir vos coordonnées. Vous pouvez toujours commander sans compte.", "account.guestCheckoutCopy": "Parcourir le catalogue et commander sans créer de compte", "account.member": "Compte client", "account.hello": "Bonjour, {name}", "account.signedInAs": "Connecté avec {email}", "account.notProvided": "Non renseigné", "account.defaultAddress": "Par défaut", "account.noSavedAddress": "Aucune adresse enregistrée. Vos prochaines options de gestion d’adresse apparaîtront ici.",
  "status.PENDING": "En attente", "status.CONFIRMED": "Confirmée", "status.PREPARING": "En préparation", "status.SHIPPED": "Expédiée", "status.DELIVERED": "Livrée", "status.CANCELLED": "Annulée",
  "footer.tagline": "Des gadgets utiles importés de Chine et sélectionnés pour le quotidien en Tunisie.", "footer.shop": "Boutique", "footer.help": "Aide", "footer.company": "JoShop", "footer.delivery": "Livraison", "footer.returns": "Retours", "footer.contact": "Contact", "footer.about": "À propos", "footer.privacy": "Confidentialité", "footer.terms": "Conditions", "footer.rights": "Tous droits réservés.",
  "language.label": "Langue", "language.fr": "Français", "language.en": "English", "language.ar": "العربية", "language.error": "Impossible de changer la langue. Réessayez.",
  "catalog.collection": "Sélection de gadgets", "catalog.showing": "Tous les produits correspondants", "catalog.tryFilters": "Essayez de retirer un ou deux filtres.", "catalog.resultsFor": "Résultats pour « {query} »", "catalog.exploreAll": "Explorer tous les produits", "catalog.searchDiscover": "Rechercher et découvrir", "catalog.trySearch": "Essayez une recherche plus large ou effacez les filtres.",
  "error.notFound": "Cette page est introuvable", "error.notFoundCopy": "Elle a peut-être été déplacée ou n’existe plus.", "error.title": "Un problème est survenu", "error.copy": "Cette page n’a pas pu être chargée. Votre panier reste enregistré : réessayez.", "error.retry": "Réessayer",
};

const en: Messages = {
  ...fr,
  "meta.title": "JoShop — Smart gadgets from China", "meta.description": "A Tunisian marketplace for useful gadgets imported from China for home, leisure, and everyday life.",
  "common.home": "Home", "common.products": "Products", "common.categories": "Categories", "common.search": "Search", "common.searchPlaceholder": "Search products or brands…", "common.account": "Account", "common.cart": "Cart", "common.wishlist": "Wishlist", "common.close": "Close", "common.menu": "Menu", "common.viewAll": "View all", "common.discover": "Discover", "common.shopNow": "Shop now", "common.exploreDeals": "Explore deals", "common.learnMore": "Learn more", "common.back": "Back", "common.continueShopping": "Continue shopping", "common.quantity": "Quantity", "common.subtotal": "Subtotal", "common.shipping": "Shipping", "common.total": "Total", "common.remove": "Remove", "common.color": "Color", "common.option": "Option", "common.stock": "Stock", "common.inStock": "In stock", "common.outOfStock": "Out of stock", "common.new": "New", "common.sale": "Sale", "common.recommended": "Recommended", "common.priceLow": "Price: low to high", "common.priceHigh": "Price: high to low", "common.topRated": "Top rated", "common.noResults": "No results", "common.clearFilters": "Clear filters",
  "nav.audio": "Audio", "nav.home": "Home", "nav.mobility": "Electric mobility", "nav.gaming": "Gaming", "nav.connected": "Connected gadgets", "nav.accessories": "Accessories", "nav.deals": "Deals",
  "hero.eyebrow": "Gadgets from China / 2026", "hero.title": "Gadgets that simplify everyday life.", "hero.copy": "Audio, home, gaming, connected gadgets, and accessories imported from China and selected for Tunisia.",
  "home.categoriesEyebrow": "Explore JoShop", "home.categoriesTitle": "Everything you need", "home.trendingEyebrow": "Most wanted", "home.trendingTitle": "Trending now", "home.newEyebrow": "Just arrived", "home.newTitle": "New arrivals", "home.flashEyebrow": "Limited-time offers", "home.flashTitle": "Flash deals", "home.mobilityEyebrow": "Move differently", "home.mobilityTitle": "Electric mobility", "home.mobilityCopy": "Reliable electric scooters and bikes built for city commutes and weekend rides.", "home.promoEyebrow": "JoShop prices", "home.promoTitle": "More useful finds. A smarter budget.", "home.promoCopy": "Useful gadgets at accessible prices, while stocks last.", "home.newsletterEyebrow": "JoShop updates", "home.newsletterTitle": "The right gadget, at the right time.", "home.newsletterCopy": "New gadgets, guides, and useful offers delivered to your inbox.", "home.newsletterLegal": "By subscribing, you agree to receive JoShop updates. Unsubscribe anytime.",
  "home.bestEyebrow": "Customer approved", "home.bestTitle": "Best sellers", "home.endsIn": "Ends in", "home.countdownLabel": "Offer ends in {hours} hours, {minutes} minutes and {seconds} seconds", "hero.products": "imported gadgets", "hero.categories": "categories", "hero.support": "order support", "newsletter.success": "You're on the list. Welcome to JoShop.", "newsletter.subscribe": "Subscribe",
  "trust.secureTitle": "Secure payment", "trust.secureCopy": "Card or cash on delivery", "trust.deliveryTitle": "Delivery in Tunisia", "trust.deliveryCopy": "Fixed 7 TND standard shipping", "trust.supportTitle": "Local support", "trust.supportCopy": "A team ready to help", "trust.returnsTitle": "Simple returns", "trust.returnsCopy": "Request a return within 14 days",
  "product.addToCart": "Add to cart", "product.buyNow": "Buy now", "product.added": "Product added to cart", "product.chooseOption": "Choose an option", "product.specifications": "Technical specifications", "product.description": "Description", "product.reviews": "Customer reviews", "product.verified": "Verified purchase", "product.sku": "SKU", "product.youMayLike": "You may also like", "product.recentlyViewed": "Recently viewed", "product.results": "products", "product.filters": "Filters", "product.brand": "Brand", "product.category": "Category", "product.price": "Price", "product.rating": "Rating", "product.availability": "Availability", "product.onlyDiscounted": "Discounted products", "product.sort": "Sort products", "product.viewImage": "View image {index} of {product}", "product.openImage": "Open enlarged product image",
  "product.sold": "sold", "product.onlyLeft": "Only {count} left in stock", "product.ready": "In stock and ready to ship", "product.deliveryCopy": "Delivery in Tunisia within 2–4 business days — 7 TND", "product.paymentCopy": "Cash on delivery · 14-day returns", "wishlist.saved": "Saved to wishlist", "wishlist.removed": "Removed from wishlist", "wishlist.addAction": "Add to wishlist", "wishlist.removeAction": "Remove from wishlist",
  "product.anyBrand": "Any brand", "product.all": "All", "product.anyRating": "Any rating", "product.inStockOnly": "In stock only", "product.applyFilters": "Apply filters",
  "product.detailsEyebrow": "Product details", "product.shippingCopy": "Standard delivery takes 2–4 business days at a fixed rate of 7 TND.", "product.returnsCopy": "Return the complete product in its original condition within 14 days.", "product.customerNotes": "Customer feedback", "product.reviewsCount": "reviews",
  "cart.title": "Your cart", "cart.emptyTitle": "Your cart is empty", "cart.emptyCopy": "Explore our imported gadgets and find something that makes everyday life easier.", "cart.summary": "Order summary", "cart.checkout": "Checkout", "cart.standardShipping": "Standard shipping", "cart.standardShippingDetail": "Delivery in Tunisia — 7 TND", "cart.updated": "Cart updated",
  "cart.selection": "Your selection", "cart.viewCart": "View cart", "cart.items": "items", "cart.discount": "Discount", "cart.taxNote": "Taxes included. Fixed standard shipping is 7 TND.",
  "wishlist.title": "Your wishlist", "wishlist.emptyTitle": "No favourites yet", "wishlist.emptyCopy": "Save products you like and find them here later.",
  "wishlist.eyebrow": "Your shortlist", "wishlist.count": "saved products. Add any favourite straight to your cart.",
  "checkout.title": "Checkout", "checkout.backToCart": "Back to cart", "checkout.contact": "Contact details", "checkout.delivery": "Delivery address", "checkout.payment": "Payment", "checkout.orderSummary": "Your order", "checkout.placeOrder": "Place order", "checkout.processing": "Processing…", "checkout.fullName": "Full name", "checkout.email": "Email", "checkout.phone": "Phone", "checkout.address": "Address", "checkout.city": "City", "checkout.governorate": "Governorate", "checkout.postalCode": "Postal code", "checkout.country": "Country", "checkout.cash": "Cash on delivery", "checkout.card": "Bank card", "checkout.note": "Delivery note (optional)", "checkout.standard": "Standard shipping — 7 TND", "checkout.express": "Express shipping — 15 TND",
  "checkout.emptyTitle": "Nothing to checkout", "checkout.emptyCopy": "Add a product before starting checkout.", "checkout.error": "We could not place your order.", "checkout.chooseGovernorate": "Choose a governorate", "checkout.deliveryMethod": "Delivery method", "checkout.standardTime": "2–4 business days", "checkout.expressLabel": "Express shipping", "checkout.expressTime": "1–2 business days", "checkout.cashCopy": "Pay when your order arrives", "checkout.comingSoon": "Coming soon", "checkout.secureCopy": "Your information is encrypted and secure.",
  "order.received": "Order received", "order.confirmed": "Order confirmed", "order.thanks": "Thank you, {name}. We'll keep you updated as your order progresses.", "order.items": "Your items", "order.next": "What happens next?", "order.nextCopy": "We'll confirm your order, prepare it, and email you a delivery update.", "order.deliveryTo": "Delivery to", "order.number": "Order", "order.track": "Track my orders", "account.title": "My account", "account.orders": "My orders",
  "account.ordersCopy": "Track deliveries and review order history", "account.wishlistCopy": "Return to products you have saved", "account.addresses": "Addresses", "account.addressesCopy": "Manage delivery locations", "account.personal": "Personal information", "account.personalCopy": "Update your profile and contact details", "account.guest": "Guest account preview", "account.welcome": "Welcome to JoShop.", "account.guestCopy": "Guest checkout remains available. These spaces are ready to connect to an authenticated account.", "account.profilePreview": "Profile preview", "account.guestShopper": "Guest shopper", "account.market": "Market", "account.tunisia": "Tunisia", "account.currency": "Preferred currency", "account.savedAddresses": "Saved addresses", "account.noAddress": "No address is saved for guest checkout. Details remain attached to each order.", "account.orderHistory": "Order history", "account.placed": "Placed", "account.viewDetails": "View details", "account.noOrders": "No orders yet", "account.noOrdersCopy": "Your order history will appear here.",
  "auth.fullName": "Full name", "auth.email": "Email", "auth.phone": "Phone (optional)", "auth.password": "Password", "auth.confirmPassword": "Confirm password", "auth.createAccount": "Create account", "auth.signIn": "Sign in", "auth.signOut": "Sign out", "auth.registering": "Creating account…", "auth.signingIn": "Signing in…", "auth.haveAccount": "Already have an account?", "auth.noAccount": "New to JoShop?", "auth.passwordRules": "Use at least 8 characters with an uppercase letter, a lowercase letter, and a number.", "auth.memberEyebrow": "Customer account", "auth.registerTitle": "Create your account", "auth.registerCopy": "Keep your orders together, save time at checkout, and access your details across devices.", "auth.loginTitle": "Welcome back", "auth.loginCopy": "Sign in to access your orders and contact details.", "auth.signInCopy": "Enter your JoShop account credentials.", "auth.secureAccountCopy": "Your credentials are protected, and your guest cart stays available.", "auth.benefitOrders": "All your orders in one place", "auth.benefitCheckout": "Contact details prefilled at checkout", "auth.benefitAddresses": "Saved addresses in your profile", "auth.invalidRegistration": "Check your details and follow the password requirements.", "auth.emailExists": "An account already uses this email address. Sign in instead.", "auth.invalidCredentials": "Incorrect email address or password.", "auth.databaseRequired": "The database must be configured before customer accounts can be created.", "auth.registrationFailed": "We could not create your account right now. Please try again.", "auth.loginFailed": "We could not sign you in right now. Please try again.",
  "account.guestTitle": "Your JoShop space", "account.guestRegistrationCopy": "Create an account to find your orders and prefill your details. You can still shop without an account.", "account.guestCheckoutCopy": "Browse the catalogue and check out without creating an account", "account.member": "Customer account", "account.hello": "Hello, {name}", "account.signedInAs": "Signed in as {email}", "account.notProvided": "Not provided", "account.defaultAddress": "Default", "account.noSavedAddress": "No saved address yet. Future address-management options will appear here.",
  "status.PENDING": "Pending", "status.CONFIRMED": "Confirmed", "status.PREPARING": "Preparing", "status.SHIPPED": "Shipped", "status.DELIVERED": "Delivered", "status.CANCELLED": "Cancelled",
  "footer.tagline": "Useful gadgets imported from China and selected for everyday life in Tunisia.", "footer.shop": "Shop", "footer.help": "Help", "footer.company": "JoShop", "footer.delivery": "Delivery", "footer.returns": "Returns", "footer.contact": "Contact", "footer.about": "About", "footer.privacy": "Privacy", "footer.terms": "Terms", "footer.rights": "All rights reserved.", "language.label": "Language", "language.fr": "Français", "language.en": "English", "language.ar": "العربية", "language.error": "We couldn't change the language. Please try again.",
  "catalog.collection": "Gadget selection", "catalog.showing": "Showing all matching products", "catalog.tryFilters": "Try clearing one or two filters.", "catalog.resultsFor": "Results for “{query}”", "catalog.exploreAll": "Explore all products", "catalog.searchDiscover": "Search and discover", "catalog.trySearch": "Try a broader search or clear the filters.",
  "error.notFound": "Page not found", "error.notFoundCopy": "It may have moved or no longer exists.", "error.title": "Something went wrong", "error.copy": "This page could not load. Your cart is still saved, so please try again.", "error.retry": "Try again",
};

const ar: Messages = {
  ...fr,
  "meta.title": "JoShop — أدوات ذكية من الصين", "meta.description": "سوق تونسي لأدوات مفيدة مستوردة من الصين للمنزل والترفيه والحياة اليومية.",
  "common.home": "الرئيسية", "common.products": "المنتجات", "common.categories": "الفئات", "common.search": "بحث", "common.searchPlaceholder": "ابحث عن منتج أو علامة…", "common.account": "الحساب", "common.cart": "السلة", "common.wishlist": "المفضلة", "common.close": "إغلاق", "common.menu": "القائمة", "common.viewAll": "عرض الكل", "common.discover": "اكتشف", "common.shopNow": "تسوّق الآن", "common.exploreDeals": "اكتشف العروض", "common.learnMore": "اعرف المزيد", "common.back": "رجوع", "common.continueShopping": "متابعة التسوق", "common.quantity": "الكمية", "common.subtotal": "المجموع الفرعي", "common.shipping": "التوصيل", "common.total": "المجموع", "common.remove": "حذف", "common.color": "اللون", "common.option": "الخيار", "common.stock": "المخزون", "common.inStock": "متوفر", "common.outOfStock": "غير متوفر", "common.new": "جديد", "common.sale": "تخفيض", "common.recommended": "مقترحة", "common.priceLow": "السعر: من الأقل", "common.priceHigh": "السعر: من الأعلى", "common.topRated": "الأعلى تقييماً", "common.noResults": "لا توجد نتائج", "common.clearFilters": "مسح الفلاتر",
  "nav.audio": "صوتيات", "nav.home": "المنزل", "nav.mobility": "تنقل كهربائي", "nav.gaming": "ألعاب", "nav.connected": "أجهزة متصلة", "nav.accessories": "إكسسوارات", "nav.deals": "عروض",
  "hero.eyebrow": "أدوات من الصين / 2026", "hero.title": "أدوات تجعل الحياة اليومية أسهل.", "hero.copy": "صوتيات ومنزل وألعاب وأجهزة متصلة وإكسسوارات مستوردة من الصين ومختارة لتونس.",
  "home.categoriesEyebrow": "اكتشف JoShop", "home.categoriesTitle": "كل ما تحتاجه", "home.trendingEyebrow": "الأكثر طلباً", "home.trendingTitle": "رائج الآن", "home.newEyebrow": "وصل حديثاً", "home.newTitle": "منتجات جديدة", "home.flashEyebrow": "عروض محدودة", "home.flashTitle": "عروض سريعة", "home.mobilityEyebrow": "تنقّل بطريقة مختلفة", "home.mobilityTitle": "التنقل الكهربائي", "home.mobilityCopy": "دراجات وسكوترات كهربائية موثوقة للتنقل داخل المدينة ونزهات نهاية الأسبوع.", "home.promoEyebrow": "أسعار JoShop", "home.promoTitle": "اكتشافات أكثر. ميزانية أذكى.", "home.promoCopy": "أدوات مفيدة بأسعار مناسبة، حسب توفر المخزون.", "home.newsletterEyebrow": "أخبار JoShop", "home.newsletterTitle": "الأداة المناسبة، في الوقت المناسب.", "home.newsletterCopy": "أدوات جديدة وأدلة وعروض مفيدة تصل إلى بريدك.", "home.newsletterLegal": "بالاشتراك، توافق على تلقي أخبار JoShop. يمكنك إلغاء الاشتراك في أي وقت.",
  "home.bestEyebrow": "موصى بها من عملائنا", "home.bestTitle": "الأكثر مبيعاً", "home.endsIn": "ينتهي خلال", "home.countdownLabel": "ينتهي العرض خلال {hours} ساعة و{minutes} دقيقة و{seconds} ثانية", "hero.products": "أداة مستوردة", "hero.categories": "فئة", "hero.support": "دعم الطلبات", "newsletter.success": "تم الاشتراك. مرحباً بك في JoShop.", "newsletter.subscribe": "اشترك",
  "trust.secureTitle": "دفع آمن", "trust.secureCopy": "بطاقة بنكية أو الدفع عند الاستلام", "trust.deliveryTitle": "توصيل في تونس", "trust.deliveryCopy": "توصيل عادي بسعر ثابت 7 د.ت", "trust.supportTitle": "دعم محلي", "trust.supportCopy": "فريق جاهز لمساعدتك", "trust.returnsTitle": "إرجاع سهل", "trust.returnsCopy": "طلب إرجاع خلال 14 يوماً",
  "product.addToCart": "أضف إلى السلة", "product.buyNow": "اشتر الآن", "product.added": "تمت إضافة المنتج", "product.chooseOption": "اختر خياراً", "product.specifications": "المواصفات التقنية", "product.description": "الوصف", "product.reviews": "آراء العملاء", "product.verified": "شراء موثّق", "product.sku": "المرجع", "product.youMayLike": "قد يعجبك أيضاً", "product.recentlyViewed": "شوهدت مؤخراً", "product.results": "منتج", "product.filters": "الفلاتر", "product.brand": "العلامة", "product.category": "الفئة", "product.price": "السعر", "product.rating": "التقييم", "product.availability": "التوفر", "product.onlyDiscounted": "منتجات مخفضة", "product.sort": "ترتيب المنتجات", "product.viewImage": "عرض الصورة {index} من {product}", "product.openImage": "تكبير صورة المنتج",
  "product.sold": "مباع", "product.onlyLeft": "بقي {count} في المخزون", "product.ready": "متوفر وجاهز للإرسال", "product.deliveryCopy": "التوصيل داخل تونس خلال 2–4 أيام عمل — 7 د.ت", "product.paymentCopy": "الدفع عند الاستلام · إرجاع خلال 14 يوماً", "wishlist.saved": "تمت الإضافة إلى المفضلة", "wishlist.removed": "تم الحذف من المفضلة", "wishlist.addAction": "أضف إلى المفضلة", "wishlist.removeAction": "احذف من المفضلة",
  "product.anyBrand": "كل العلامات", "product.all": "الكل", "product.anyRating": "كل التقييمات", "product.inStockOnly": "المتوفر فقط", "product.applyFilters": "تطبيق الفلاتر",
  "product.detailsEyebrow": "تفاصيل المنتج", "product.shippingCopy": "التوصيل العادي خلال 2–4 أيام عمل بسعر ثابت 7 د.ت.", "product.returnsCopy": "يمكن إرجاع المنتج كاملاً وفي حالته الأصلية خلال 14 يوماً.", "product.customerNotes": "آراء العملاء", "product.reviewsCount": "تقييم",
  "cart.title": "سلة التسوق", "cart.emptyTitle": "سلتك فارغة", "cart.emptyCopy": "اكتشف أدواتنا المستوردة واختر ما يسهّل حياتك اليومية.", "cart.summary": "ملخص الطلب", "cart.checkout": "إتمام الطلب", "cart.standardShipping": "التوصيل العادي", "cart.standardShippingDetail": "توصيل داخل تونس — 7 د.ت", "cart.updated": "تم تحديث السلة",
  "cart.selection": "اختياراتك", "cart.viewCart": "عرض السلة", "cart.items": "منتج", "cart.discount": "التخفيض", "cart.taxNote": "الضرائب مشمولة. التوصيل العادي ثابت بسعر 7 د.ت.",
  "wishlist.title": "المفضلة", "wishlist.emptyTitle": "لا توجد منتجات مفضلة", "wishlist.emptyCopy": "احفظ المنتجات التي تهمك لتجدها هنا لاحقاً.",
  "wishlist.eyebrow": "اختياراتك", "wishlist.count": "منتج محفوظ. أضف ما يعجبك مباشرة إلى السلة.",
  "checkout.title": "إتمام الطلب", "checkout.backToCart": "العودة إلى السلة", "checkout.contact": "بيانات الاتصال", "checkout.delivery": "عنوان التوصيل", "checkout.payment": "الدفع", "checkout.orderSummary": "طلبك", "checkout.placeOrder": "تأكيد الطلب", "checkout.processing": "جارٍ التنفيذ…", "checkout.fullName": "الاسم الكامل", "checkout.email": "البريد الإلكتروني", "checkout.phone": "الهاتف", "checkout.address": "العنوان", "checkout.city": "المدينة", "checkout.governorate": "الولاية", "checkout.postalCode": "الترقيم البريدي", "checkout.country": "البلد", "checkout.cash": "الدفع عند الاستلام", "checkout.card": "بطاقة بنكية", "checkout.note": "ملاحظة للتوصيل (اختياري)", "checkout.standard": "توصيل عادي — 7 د.ت", "checkout.express": "توصيل سريع — 15 د.ت",
  "checkout.emptyTitle": "لا يوجد طلب لإتمامه", "checkout.emptyCopy": "أضف منتجاً قبل البدء.", "checkout.error": "تعذر تسجيل طلبك.", "checkout.chooseGovernorate": "اختر الولاية", "checkout.deliveryMethod": "طريقة التوصيل", "checkout.standardTime": "2–4 أيام عمل", "checkout.expressLabel": "توصيل سريع", "checkout.expressTime": "1–2 يوم عمل", "checkout.cashCopy": "ادفع عند استلام طلبك", "checkout.comingSoon": "قريباً", "checkout.secureCopy": "معلوماتك مشفرة وآمنة.",
  "order.received": "تم استلام الطلب", "order.confirmed": "تم تأكيد الطلب", "order.thanks": "شكراً {name}. سنطلعك على مراحل تقدم طلبك.", "order.items": "منتجاتك", "order.next": "ما الخطوة التالية؟", "order.nextCopy": "سنؤكد طلبك ونحضّره ثم نرسل تحديث التوصيل عبر البريد الإلكتروني.", "order.deliveryTo": "التوصيل إلى", "order.number": "الطلب", "order.track": "متابعة طلباتي", "account.title": "حسابي", "account.orders": "طلباتي",
  "account.ordersCopy": "تتبع التوصيل وراجع سجل الطلبات", "account.wishlistCopy": "ارجع إلى المنتجات التي حفظتها", "account.addresses": "العناوين", "account.addressesCopy": "إدارة عناوين التوصيل", "account.personal": "المعلومات الشخصية", "account.personalCopy": "تحديث الملف وبيانات الاتصال", "account.guest": "معاينة حساب الضيف", "account.welcome": "مرحباً بك في JoShop.", "account.guestCopy": "يبقى الدفع كضيف متاحاً. هذه المساحات جاهزة للربط بحساب موثّق.", "account.profilePreview": "معاينة الملف", "account.guestShopper": "عميل ضيف", "account.market": "السوق", "account.tunisia": "تونس", "account.currency": "العملة المفضلة", "account.savedAddresses": "العناوين المحفوظة", "account.noAddress": "لا يوجد عنوان محفوظ للدفع كضيف. تبقى البيانات مرتبطة بكل طلب.", "account.orderHistory": "سجل الطلبات", "account.placed": "تم الطلب في", "account.viewDetails": "عرض التفاصيل", "account.noOrders": "لا توجد طلبات", "account.noOrdersCopy": "سيظهر سجل طلباتك هنا.",
  "auth.fullName": "الاسم الكامل", "auth.email": "البريد الإلكتروني", "auth.phone": "الهاتف (اختياري)", "auth.password": "كلمة المرور", "auth.confirmPassword": "تأكيد كلمة المرور", "auth.createAccount": "إنشاء حساب", "auth.signIn": "تسجيل الدخول", "auth.signOut": "تسجيل الخروج", "auth.registering": "جارٍ إنشاء الحساب…", "auth.signingIn": "جارٍ تسجيل الدخول…", "auth.haveAccount": "لديك حساب بالفعل؟", "auth.noAccount": "جديد في JoShop؟", "auth.passwordRules": "استخدم 8 أحرف على الأقل مع حرف كبير وحرف صغير ورقم.", "auth.memberEyebrow": "فضاء الحريف", "auth.registerTitle": "أنشئ حسابك", "auth.registerCopy": "اجمع طلباتك في مكان واحد ووفر الوقت عند الدفع واطّلع على بياناتك من مختلف الأجهزة.", "auth.loginTitle": "مرحباً بعودتك", "auth.loginCopy": "سجّل الدخول للوصول إلى طلباتك وبيانات الاتصال.", "auth.signInCopy": "أدخل بيانات حسابك في JoShop.", "auth.secureAccountCopy": "بيانات الدخول محمية وتبقى سلة الضيف متاحة.", "auth.benefitOrders": "كل طلباتك في مكان واحد", "auth.benefitCheckout": "تعبئة بيانات الاتصال تلقائياً عند الدفع", "auth.benefitAddresses": "عناوين محفوظة في ملفك", "auth.invalidRegistration": "تحقق من بياناتك والتزم بشروط كلمة المرور.", "auth.emailExists": "يوجد حساب بهذا البريد الإلكتروني. سجّل الدخول بدلاً من ذلك.", "auth.invalidCredentials": "البريد الإلكتروني أو كلمة المرور غير صحيح.", "auth.databaseRequired": "يجب إعداد قاعدة البيانات قبل إنشاء حسابات الحرفاء.", "auth.registrationFailed": "تعذر إنشاء الحساب حالياً. حاول مرة أخرى.", "auth.loginFailed": "تعذر تسجيل الدخول حالياً. حاول مرة أخرى.",
  "account.guestTitle": "فضاؤك في JoShop", "account.guestRegistrationCopy": "أنشئ حساباً للعثور على طلباتك وتعبئة بياناتك تلقائياً. يمكنك مواصلة الشراء دون حساب.", "account.guestCheckoutCopy": "تصفح المنتجات وأكمل الطلب دون إنشاء حساب", "account.member": "حساب الحريف", "account.hello": "مرحباً، {name}", "account.signedInAs": "تم الدخول بواسطة {email}", "account.notProvided": "غير متوفر", "account.defaultAddress": "افتراضي", "account.noSavedAddress": "لا يوجد عنوان محفوظ بعد. ستظهر هنا خيارات إدارة العناوين لاحقاً.",
  "status.PENDING": "في الانتظار", "status.CONFIRMED": "مؤكد", "status.PREPARING": "قيد التحضير", "status.SHIPPED": "تم الإرسال", "status.DELIVERED": "تم التوصيل", "status.CANCELLED": "ملغى",
  "footer.tagline": "أدوات مفيدة مستوردة من الصين ومختارة للحياة اليومية في تونس.", "footer.shop": "المتجر", "footer.help": "مساعدة", "footer.company": "JoShop", "footer.delivery": "التوصيل", "footer.returns": "الإرجاع", "footer.contact": "اتصل بنا", "footer.about": "من نحن", "footer.privacy": "الخصوصية", "footer.terms": "الشروط", "footer.rights": "جميع الحقوق محفوظة.", "language.label": "اللغة", "language.fr": "Français", "language.en": "English", "language.ar": "العربية", "language.error": "تعذر تغيير اللغة. حاول مرة أخرى.",
  "catalog.collection": "اختيارات من الأدوات", "catalog.showing": "عرض كل المنتجات المطابقة", "catalog.tryFilters": "جرّب إزالة فلتر أو اثنين.", "catalog.resultsFor": "نتائج البحث عن « {query} »", "catalog.exploreAll": "اكتشف كل المنتجات", "catalog.searchDiscover": "ابحث واكتشف", "catalog.trySearch": "جرّب بحثاً أوسع أو امسح الفلاتر.",
  "error.notFound": "الصفحة غير موجودة", "error.notFoundCopy": "ربما تم نقلها أو لم تعد موجودة.", "error.title": "حدث خطأ", "error.copy": "تعذر تحميل الصفحة. سلتك محفوظة، يرجى المحاولة مجدداً.", "error.retry": "أعد المحاولة",
};

export const dictionaries: Record<Locale, Messages> = { fr, en, ar };

export function interpolate(message: string, values?: Record<string, string | number>) {
  if (!values) return message;
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), message);
}
